name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/computer-use-mcp
    permissions:
      id-token: write  # IMPORTANT: Required for trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Verify package version
        run: |
          VERSION=$(grep -oP '^version = "\K[^"]+' pyproject.toml)
          echo "Package version: $VERSION"
          if [ -z "$VERSION" ]; then
            echo "Error: Could not extract version from pyproject.toml"
            exit 1
          fi

      - name: Build package
        run: uv build

      - name: Verify build artifacts
        run: |
          ls -lh dist/
          echo "---"
          echo "Built packages:"
          ls dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Uses PyPI Trusted Publishers - no token needed!
          # Configure at: https://pypi.org/manage/account/publishing/
          verbose: true
          print-hash: true

      - name: Create build summary
        if: success()
        run: |
          echo "## ✅ Published Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Package:** computer-use-mcp" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** $(grep -oP '^version = "\K[^"]+' pyproject.toml)" >> $GITHUB_STEP_SUMMARY
          echo "**PyPI:** https://pypi.org/project/computer-use-mcp/" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Users can now install with:" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "uvx computer-use-mcp" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
