name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --all-extras
          uv run playwright install chromium --with-deps

      - name: Run validation tests
        run: uv run python test_server.py

      - name: Test package build
        run: uv build

      - name: Verify built package
        run: |
          echo "Built packages:"
          ls -lh dist/

      - name: Test summary
        if: success()
        run: |
          echo "## ✅ Tests Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Python:** ${{ matrix.python-version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Platform:** ubuntu-latest" >> $GITHUB_STEP_SUMMARY

  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        uses: astral-sh/setup-uv@v4

      - name: Check Python syntax
        run: |
          uv run python -m py_compile server.py browser_agent.py task_manager.py test_server.py

      - name: Lint summary
        if: success()
        run: |
          echo "## ✅ Linting Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All Python files have valid syntax" >> $GITHUB_STEP_SUMMARY
